# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-deployment
spec:
  # CLAVE DE ALTA DISPONIBILIDAD: Mínimo 2 Pods
  replicas: 2 
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
      - name: go-web
        # Usa la imagen que tu pipeline de Jenkins está construyendo
        image: mi_aplicacion_go:latest 
        ports:
        - containerPort: 8080
---
# Service: Balanceador de Carga
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  selector:
    app: go-web
  ports:
    # El tráfico externo al puerto 80 del host se dirige al puerto 8080 del contenedor
    - protocol: TCP
      port: 80
      targetPort: 8080
  # K3s usa el tipo NodePort en lugar de LoadBalancer para exposiciones locales.
  type: NodePort
